name: Release
on: workflow_dispatch
jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install the dependancies
      run: npm ci

    - name: Initialize Git user
      run: |
        git config user.name "GitHub Action Bot"
        git config user.email "<>"

    - name: Run release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        if [ ${{github.ref_name}} == 'main' ]; then
          npx release-it --ci
        elif [ ${{github.ref_name}} == 'dev' ]; then
          npx release-it --preRelease=rc --ci
        else
          npx release-it --preRelease=${{github.ref_name}} --no-github.release --ci
        fi
        version=$(jq -r '.version' package.json)
        echo $version